### PR TITLE
Remove custom malloc

### PR DESCRIPTION
**Pull request by andronat**
Removed SaBRe's custom malloc as it is not used. 

Also removed a couple of superfluous statements that are duplicates of [here](https://github.com/srg-imperial/SaBRe/blob/master/cmake/sabre_add_component.cmake#L18) and [here](https://github.com/srg-imperial/SaBRe/blob/master/includes/macros.h#L34).

### CODE REVIEW

**Comment by ccadar** [comment]
@andronat Are you sure we want to remove it?  I thought you're considering bringing it back.
@parras What is your take?

**Comment by parras** [comment]
I think the idea is to replace this old, unreliable malloc with mimalloc -- which is fine. @andronat  is that correct?

**Comment by andronat** [comment]
Yep! That’s exactly the plan as @parras says.

**Comment by ccadar** [comment]
Thanks, I'm then ok to remove this.

**Pull request merged**
