### PR TITLE
Switch asm to MIT license and move to plugin_api/

### PR DESCRIPTION
**Pull request by jasonwhite**
These files need to be statically linked into plugins. Since they're GPL-3, that means the plugin itself would also need to be GPL-3. This isn't really feasible in many cases and so MIT is a much better fit for these files.

### CODE REVIEW

**Comment by andronat** [comment]
I was actually moving those myself [here](https://github.com/andronat/SaBRe/commit/bf5fc6aa599e98c4568d7600b1e0be4f17656304) but let's merge these!

**Comment by jasonwhite** [comment]
@andronat Oops! Didn't see that one. Thanks for merging this!

**Comment by ccadar** [comment]
@andronat @jasonwhite I don't think you should have merged this before hearing back from @parras who (co-)authored them.  Could you please revert it until we hear back?

**Comment by ccadar** [comment]
Note that the license you updated previously in #64  was for a file only authored by you, I approved it, and we waited for others to comment.  We should follow a similar process here, especially with files (co-)authored by others.  I also know @parras had concerns about the license so I'd like to explicitly hear from him.  

@parras let us know you thoughts.  If I don't hear from you on GitHub, I'll try email. On my side, I support this change, as I understand that we should allow plugin code to be private.  And the benefits for SaBRe are that the core will continue to receive updates, under the current GPL 3 license.

**Comment by andronat** [comment]
I’ll revert it asap for the 2 files i’m not the sole author. For ‘clone3’ we are ok.

**Comment by parras** [comment]
@ccadar Thanks for pinging me over this! I agree with you, plugin code can be private, as long as the core SaBRe stays under GPLv3. So this MR is fine with me, no need to revert it!

**Comment by ccadar** [comment]
Thanks for the quick reply, @parras, that's great.
And thanks, @andronat and @jasonwhite for the recent useful changes!

**Pull request merged**
