### PR TITLE
Add Travis config file

### PR DESCRIPTION
**Pull request by parras**
If Travis is correctly set up in the repo, this PR should trigger a build...

### CODE REVIEW

**Comment by ccadar** [comment]
Thanks, @parras!  What's the status here?  I feel this PR should have the highest priority, as we should have CI in place going forward.

**Comment by ccadar** [comment]
@parras, now that #42 is in, can you rebase this to see if Travis CI is working now?  Thanks!

**Comment by parras** [comment]
It's getting better but we still have a couple of failures. I'm looking into this now.

**Comment by parras** [comment]
Passed. Feel free to merge if you're OK with the latests commits.

**Comment by ccadar** [comment]
@parras Woohoo, nice to see the Travis CI go green!

**Pull request merged**
