### PR TITLE
Segregate SaBRe and client malloc arenas with mallopt

### PR DESCRIPTION
**Pull request by andronat**
There 2 mallocs in memory because SaBRe loads 2 libcs (one for SaBRe) and one for the client (which is intercepted). These two mallocs will overlap their arenas as malloc uses brk(NULL) to initialize its arena, and this brk(NULL) will always return the same pointer. To avoid this we force SaBRe's malloc to completely skip the arena initialization and keep objects into separate mmap() pages. 

This of course comes with a small performance decrease, and the potential to OOM if we allocate too many items.

### CODE REVIEW

**Comment by daniel-grumberg** [comment]
Can you remove the formatting changes you made?

**Comment by andronat** [comment]
The current format changes are from `git clang-format`.

**Comment by ccadar** [comment]
@andronat thanks.  Does this mean that we won't use @parras 's malloc implementation?
Also, why did you change `MAX_INITIAL_MAPPINGS`?

**Comment by andronat** [comment]
This PR has nothing do to with the underlying malloc. Normally, the internal malloc should had been used rather than the libc’s. We do know that there is another bug that prohibits this, but it’s irrelevant. I’m removing our custom malloc at a later PR where I replace it with MiMalloc.

The static array keeps track of some rewritten pages. On a couple tests I run on my machine required some more space for some reason.

**Pull request merged**
